### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by fallenleavesgocrunch** [flysand7/odin-sqlite3#1]
Hey there. Simple change to add support for macOS too:

when ODIN_OS == .Windows {
    foreign import sqlite3 "bin/sqlite3.lib"
} else when ODIN_OS ==.Linux {
    foreign import sqlite3 {
        "bin/sqlite3.a",
        "system:pthread",
        "system:dl",
        "system:m",
    }
} else when ODIN_OS == .Darwin {
    foreign import sqlite3 "system:/usr/lib/sqlite3/libtclsqlite3.dylib"
}

**Comment by flysand7** [comment]
Are you using macOS? In that case can you try changing the import line to

```
foreign import sqlite3 "system:sqlite3"
```

And seeing if that works? The code that you have suggested doesn't seem to be right to me. We don't write `system:` to then specify the absolute path to the library, because it's supposed to be for libraries that you have to find "somewhere" in the system, not in a very specific place that can change between systems.

**Comment by willowless** [comment]
Yep that works. I also added BLOB type (as i've got some uuid primary keys) to map to []u8 in my local copy. I haven't tested it well though.

**Comment by flysand7** [comment]
If you have a specific change you'd like to see, feel free to fork this repository and making a Pull Request. I'll look at it and merge it, this would help a lot.
